/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import clases.Cuenta;
import javax.swing.JOptionPane;

/**
 *
 * @author Lorenzo
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    Cuenta c;
    public Principal() {
        initComponents();
        txtNumeroCuenta.setEditable(true);
        txtNumeroID.setEditable(true);
        txtSaldoActual.setEditable(true);

        cmdCrear.setEnabled(true);
        cmdIngresar.setEnabled(false);
        cmdRetirar.setEnabled(false);
        cmdActualizar.setEnabled(false);
        cmdMostrar.setEnabled(false);
        cmdLimpiar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        cmdCrear = new javax.swing.JButton();
        cmdIngresar = new javax.swing.JButton();
        cmdRetirar = new javax.swing.JButton();
        cmdActualizar = new javax.swing.JButton();
        cmdMostrar = new javax.swing.JButton();
        cmdLimpiar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtNumeroCuenta = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNumeroID = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtSaldoActual = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtResultado = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CUENTA");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 11, 130, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmdCrear.setText("Crear Cuenta");
        cmdCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCrearActionPerformed(evt);
            }
        });
        jPanel2.add(cmdCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 140, 40));

        cmdIngresar.setText("Ingresar");
        cmdIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdIngresarActionPerformed(evt);
            }
        });
        jPanel2.add(cmdIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 140, 40));

        cmdRetirar.setText("Retirar");
        cmdRetirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdRetirarActionPerformed(evt);
            }
        });
        jPanel2.add(cmdRetirar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 140, 40));

        cmdActualizar.setText("Actualizar Saldo");
        cmdActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdActualizarActionPerformed(evt);
            }
        });
        jPanel2.add(cmdActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 140, 40));

        cmdMostrar.setText("Mostrar");
        cmdMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdMostrarActionPerformed(evt);
            }
        });
        jPanel2.add(cmdMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 140, 40));

        cmdLimpiar.setText("Limpiar");
        cmdLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdLimpiarActionPerformed(evt);
            }
        });
        jPanel2.add(cmdLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 323, 140, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 160, 390));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Número de Cuenta:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 110, 20));

        txtNumeroCuenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumeroCuentaKeyTyped(evt);
            }
        });
        jPanel1.add(txtNumeroCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 110, 30));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Número de Identificación: ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 130, 20));

        txtNumeroID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumeroIDKeyTyped(evt);
            }
        });
        jPanel1.add(txtNumeroID, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 110, 30));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Saldo Actual:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 120, 20));

        txtSaldoActual.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSaldoActualKeyTyped(evt);
            }
        });
        jPanel1.add(txtSaldoActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 110, 30));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultado"));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtResultado.setEditable(false);
        txtResultado.setColumns(20);
        txtResultado.setRows(5);
        jScrollPane1.setViewportView(txtResultado);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 240, 150));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 260, 180));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(520, 480));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmdCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCrearActionPerformed
        if (txtNumeroCuenta.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Espacio Vacío, Favor Llénelo", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtNumeroCuenta.requestFocusInWindow();
        } else if (txtNumeroID.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Espacio Vacío, Favor Llénelo", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtNumeroID.requestFocusInWindow();
        } else if (txtSaldoActual.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Espacio Vacío, Favor Llénelo", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtSaldoActual.requestFocusInWindow();
        } else {
            long n_cuenta,n_id;
            double s_actual;
            n_cuenta = Long.parseLong(txtNumeroCuenta.getText());
            n_id = Long.parseLong(txtNumeroID.getText());
            s_actual = Double.parseDouble(txtSaldoActual.getText());
            c = new Cuenta(n_cuenta,n_id,s_actual);
            JOptionPane.showMessageDialog(this, "¡Cuenta Creada Exitosamente!");
            txtNumeroCuenta.setEditable(false);
            txtNumeroID.setEditable(false);
            txtSaldoActual.setEditable(false);

            cmdCrear.setEnabled(false);
            cmdIngresar.setEnabled(true);
            cmdRetirar.setEnabled(true);
            cmdActualizar.setEnabled(true);
            cmdMostrar.setEnabled(true);
            cmdLimpiar.setEnabled(true);
        }
    }//GEN-LAST:event_cmdCrearActionPerformed

    private void cmdIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdIngresarActionPerformed
        double aux;
        int sw = 0;
        do {
            try {
                aux = Double.parseDouble(JOptionPane.showInputDialog(this, "Digite Cantidad a ingresar"));
                if (aux < 1) {
                    JOptionPane.showMessageDialog(this, "digite un numero valido", "Error", JOptionPane.ERROR_MESSAGE);
                    sw = 0;
                } else {
                    c.ingresar(aux);
                    sw = 1;
                    txtNumeroCuenta.setEditable(false);
                    txtNumeroID.setEditable(false);
                    txtSaldoActual.setEditable(false);

                    cmdCrear.setEnabled(false);
                    cmdIngresar.setEnabled(true);
                    cmdRetirar.setEnabled(true);
                    cmdActualizar.setEnabled(true);
                    cmdMostrar.setEnabled(true);
                    cmdLimpiar.setEnabled(true);
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "digite un numero valido", "Error", JOptionPane.ERROR_MESSAGE);
                sw = 0;
            } catch (NullPointerException e) {
                int aux2 = JOptionPane.showConfirmDialog(this, "¿Seguro que deseas salir?", "Salir", JOptionPane.YES_NO_OPTION);
                if (aux2 == 0) {
                    sw = 1;
                } else {
                    sw = 0;
                }
            }
        } while (sw == 0);
    }//GEN-LAST:event_cmdIngresarActionPerformed

    private void cmdRetirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdRetirarActionPerformed
        double aux;
        int sw = 0;
        aux = Double.parseDouble(JOptionPane.showInputDialog(this, "Digite El Valor a Egresar en la Cuenta"));
        do {
            try {
                if (aux > c.getSaldo_actual()) {
                    JOptionPane.showMessageDialog(this, "La Cantidad que quiere retirar es mayor a su saldo");
                    sw = 0;
                } else if (aux < 0) {
                    JOptionPane.showMessageDialog(this, "Digite una cantidad válida", "ERROR", JOptionPane.ERROR_MESSAGE);
                    sw = 0;
                } else {
                    c.ingresar(aux);
                    sw = 1;
                    
                    txtNumeroCuenta.setEditable(false);
                    txtNumeroID.setEditable(false);
                    txtSaldoActual.setEditable(false);

                    cmdCrear.setEnabled(false);
                    cmdIngresar.setEnabled(true);
                    cmdRetirar.setEnabled(true);
                    cmdActualizar.setEnabled(true);
                    cmdMostrar.setEnabled(true);
                    cmdLimpiar.setEnabled(true);
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Digite un Número Válido", "ERROR", JOptionPane.ERROR_MESSAGE);
            } catch (NullPointerException e) {
                int aux2 = JOptionPane.showConfirmDialog(this, "¿Seguro que Desea Salir?", "SALIR", JOptionPane.YES_NO_OPTION);
                if (aux2 == 0) {
                    sw = 1;
                } else {
                    sw = 0;
                }
            }
        } while (sw == 0);


    }//GEN-LAST:event_cmdRetirarActionPerformed

    private void cmdActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdActualizarActionPerformed
        double interesan;
        int sw = 0;
        interesan = Double.parseDouble(JOptionPane.showInputDialog(this, "Digite el Interés Anual"));
        do {
            try {
                if (interesan < 0) {
                    JOptionPane.showMessageDialog(this, "Digite una Cantidad Válida", "ERROR", JOptionPane.ERROR_MESSAGE);
                    sw = 0;
                } else {
                    c.actualizarSaldo(interesan);
                    sw = 1;
                    txtNumeroCuenta.setEditable(false);
                    txtNumeroID.setEditable(false);
                    txtSaldoActual.setEditable(false);

                    cmdCrear.setEnabled(false);
                    cmdIngresar.setEnabled(true);
                    cmdRetirar.setEnabled(true);
                    cmdActualizar.setEnabled(true);
                    cmdMostrar.setEnabled(true);
                    cmdLimpiar.setEnabled(true);
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Digite un Número Válido", "ERROR", JOptionPane.ERROR_MESSAGE);
            } catch (NullPointerException e) {
                int aux = JOptionPane.showConfirmDialog(this, "¿Seguro que Desea Salir?", "SALIR", JOptionPane.YES_NO_OPTION);
                if (aux == 0) {
                    sw = 1;
                } else {
                    sw = 0;
                }
            }
        } while (sw == 0);
    }//GEN-LAST:event_cmdActualizarActionPerformed

    private void cmdMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdMostrarActionPerformed
        String aux;
        aux = c.mostrar();
        txtResultado.setText(aux);

        txtNumeroCuenta.setEditable(false);
        txtNumeroID.setEditable(false);
        txtSaldoActual.setEditable(false);

        cmdCrear.setEnabled(false);
        cmdIngresar.setEnabled(true);
        cmdRetirar.setEnabled(true);
        cmdActualizar.setEnabled(true);
        cmdMostrar.setEnabled(false);
        cmdLimpiar.setEnabled(true);
    }//GEN-LAST:event_cmdMostrarActionPerformed

    private void cmdLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLimpiarActionPerformed
        txtNumeroCuenta.setText("");
        txtNumeroID.setText("");
        txtSaldoActual.setText("");
        txtResultado.setText("");

        txtNumeroCuenta.requestFocusInWindow();

        txtNumeroCuenta.setEditable(true);
        txtNumeroID.setEditable(true);
        txtSaldoActual.setEditable(true);

        cmdCrear.setEnabled(true);
        cmdIngresar.setEnabled(false);
        cmdRetirar.setEnabled(false);
        cmdActualizar.setEnabled(false);
        cmdMostrar.setEnabled(true);
        cmdLimpiar.setEnabled(false);

    }//GEN-LAST:event_cmdLimpiarActionPerformed

    private void txtNumeroCuentaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroCuentaKeyTyped
        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            getToolkit().beep();

            evt.consume();
        }
    }//GEN-LAST:event_txtNumeroCuentaKeyTyped

    private void txtNumeroIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroIDKeyTyped
        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            getToolkit().beep();

            evt.consume();
        }
    }//GEN-LAST:event_txtNumeroIDKeyTyped

    private void txtSaldoActualKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSaldoActualKeyTyped
        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            getToolkit().beep();

            evt.consume();
        }
    }//GEN-LAST:event_txtSaldoActualKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdActualizar;
    private javax.swing.JButton cmdCrear;
    private javax.swing.JButton cmdIngresar;
    private javax.swing.JButton cmdLimpiar;
    private javax.swing.JButton cmdMostrar;
    private javax.swing.JButton cmdRetirar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtNumeroCuenta;
    private javax.swing.JTextField txtNumeroID;
    private javax.swing.JTextArea txtResultado;
    private javax.swing.JTextField txtSaldoActual;
    // End of variables declaration//GEN-END:variables
}
